pipeline {
   environment {
     registry = '621650508462.dkr.ecr.us-east-1.amazonaws.com/springboot-backend'
     registryCredential = 'aws-credentials'
     dockerImage = ''
   }
   agent any
   stages {
         stage("Env Variables") {
             steps {
                     sh "printenv"
             }
         }
         stage('UnitTests') {
             when {
                 expression {
                     return env.GIT_BRANCH != "origin/main"
                 }
             }
             steps {
                 dir("springboot-backend"){
                     sh 'mvn test -Dgroups="UnitTests"'
                 }
             }
         }
         stage('Package') {
             steps {
                 dir("springboot-backend"){
                     sh 'mvn package -DskipTests'
                 }
             }
         }

         stage('Building docker image') {
             when {
                 expression {
                     return env.GIT_BRANCH == "origin/main"
                 }
             }
             steps {
                 dir("springboot-backend") {
                     script {
                         dockerImage = docker.build registry
                     }
                 }
             }
         }
         stage('Deploy image to AWS ECR') {
             when {
                 expression {
                     return env.GIT_BRANCH == "origin/main"
                 }
             }
             steps {
                 script {
                     docker.withRegistry("https://" + registry, "ecr:us-east-1:" + registryCredential) {
                         dockerImage.push("${env.BUILD_NUMBER}")
                         dockerImage.push("latest")
                     }
                 }
             }
         }
   }
 }