pipeline {
   environment {
     registry = '621650508462.dkr.ecr.us-east-1.amazonaws.com/springboot-backend'
     registryCredential = 'aws-credentials'
     dockerImage = ''
   }
   agent any
   stages {
         stage('Unit Tests') {
             when {
                allOf {
                    changeset pattern: "springboot-backend/*"
                    expression {
                     return env.GIT_BRANCH != "origin/main"
                    }
                }
             }
             steps {
                 dir("springboot-backend"){
                     sh 'mvn test -Dgroups="UnitTests"'
                 }
             }
         }
         stage('Integration Tests') {
            when {
                allOf {
                    changeset pattern: "springboot-backend/*"
                    expression {
                     return env.GIT_BRANCH == "origin/main"
                    }
                }
            }
            steps {
                dir("springboot-backend"){
                    sh 'mvn test -Dgroups="IntegrationTests"'
                }
            }
         }
         stage('Package') {
            when {
                changeset pattern: "springboot-backend/*"
            }
             steps {
                 dir("springboot-backend"){
                     sh 'mvn package -DskipTests'
                 }
             }
         }

         stage('Building docker image') {
             when {
                allOf {
                    changeset pattern: "springboot-backend/*"
                    expression {
                     return env.GIT_BRANCH == "origin/main"
                    }
                }
             }
             steps {
                 dir("springboot-backend") {
                     script {
                         dockerImage = docker.build registry
                     }
                 }
             }
         }
         stage('Deploy image to AWS ECR') {
             when {
                allOf {
                    changeset pattern: "springboot-backend/*"
                    expression {
                     return env.GIT_BRANCH == "origin/main"
                    }
                }
             }
             steps {
                 script {
                     docker.withRegistry("https://" + registry, "ecr:us-east-1:" + registryCredential) {
                         dockerImage.push("${env.BUILD_NUMBER}")
                         dockerImage.push("latest")
                     }
                 }
             }
         }
   }
 }