name: springboot-backend-pr

# Controls when the action will run. 
on:
  pull_request:
    types: [ opened,synchronize]
    branches:
      - master
    
    paths:
      - 'springboot-backend/**'
env:
  SERVICE_DIR: 'springboot-backend'

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ${{ vars.SERVICE_DIR }}
        run: mvn test -Dgroups="IntegrationTests"