name: springboot-backend-ci

# Controls when the action will run. 
on:
  push:
    branches:
      - 'feat/**'
      - 'bugfix/**'
      - 'hotfix/**'
    # paths:
    #   - 'springboot-backend/**'

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./springboot-backend
        run: mvn test -Dgroups="UnitTests"