name: springboot-backend-cd

# Controls when the action will run. 
on:
  push:
    branches:
      - 'master'
    paths:
      - 'springboot-backend/**'
env:
  SERVICE_DIR: 'springboot-backend'
  SERVICE_NAME: 'springboot-backend'
  CLUSTER_NAME: 'fullstack-spring-boot'

jobs:
  deployment:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        working-directory: ${{ env.SERVICE_DIR }}
        run: mvn package -DskipTests
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, push to AWS ECR
        working-directory: ${{ env.SERVICE_DIR }}
        id: build
        env:
          REPOSITORY_URL: ${{ steps.login-ecr.outputs.registry }}/${{ env.SERVICE_NAME }}
        run: |
          docker build -t ${{ env.REPOSITORY_URL }} .
          docker push ${{ env.REPOSITORY_URL }}
      - name : Force new AWS ECS deployment
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --force-new-deployment
